# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FLmon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FLmon.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x46Lmon.proto\"\x1c\n\x0c\x46LmonRequest\x12\x0c\n\x04type\x18\x01 \x01(\x05\"}\n\x16\x46LmonRequestManagement\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0b\n\x03\x63ri\x18\x02 \x01(\x05\x12\x16\n\tacc_class\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08rou_pred\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x0c\n\n_acc_classB\x0b\n\t_rou_pred\"\xc5\x01\n\rFLmonResponse\x12\x0b\n\x03\x61\x63\x63\x18\x01 \x01(\t\x12\x0b\n\x03tel\x18\x02 \x01(\t\x12\x0b\n\x03trl\x18\x03 \x01(\t\x12\x0b\n\x03rou\x18\x04 \x01(\t\x12\x0b\n\x03\x63lc\x18\x05 \x01(\t\x12\x0b\n\x03\x65nt\x18\x06 \x01(\t\x12\x0b\n\x03trt\x18\x07 \x01(\t\x12\x0b\n\x03upt\x18\x08 \x01(\t\x12\x0b\n\x03\x64it\x18\t \x01(\t\x12\x0b\n\x03\x61gt\x18\n \x01(\t\x12\x0b\n\x03\x63ld\x18\x0b \x01(\t\x12\x0b\n\x03pre\x18\x0c \x01(\t\x12\x0b\n\x03sul\x18\r \x01(\t\x12\x0b\n\x03\x63rl\x18\x0e \x01(\t\"\x19\n\x17\x46LmonResponseManagement2:\n\x05\x46Lmon\x12\x31\n\x0etransportFLmon\x12\r.FLmonRequest\x1a\x0e.FLmonResponse\"\x00\x62\x06proto3'
)




_FLMONREQUEST = _descriptor.Descriptor(
  name='FLmonRequest',
  full_name='FLmonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='FLmonRequest.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=43,
)


_FLMONREQUESTMANAGEMENT = _descriptor.Descriptor(
  name='FLmonRequestManagement',
  full_name='FLmonRequestManagement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='FLmonRequestManagement.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cri', full_name='FLmonRequestManagement.cri', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='acc_class', full_name='FLmonRequestManagement.acc_class', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rou_pred', full_name='FLmonRequestManagement.rou_pred', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_acc_class', full_name='FLmonRequestManagement._acc_class',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_rou_pred', full_name='FLmonRequestManagement._rou_pred',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=45,
  serialized_end=170,
)


_FLMONRESPONSE = _descriptor.Descriptor(
  name='FLmonResponse',
  full_name='FLmonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='acc', full_name='FLmonResponse.acc', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tel', full_name='FLmonResponse.tel', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trl', full_name='FLmonResponse.trl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rou', full_name='FLmonResponse.rou', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clc', full_name='FLmonResponse.clc', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ent', full_name='FLmonResponse.ent', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trt', full_name='FLmonResponse.trt', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upt', full_name='FLmonResponse.upt', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dit', full_name='FLmonResponse.dit', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='agt', full_name='FLmonResponse.agt', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cld', full_name='FLmonResponse.cld', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pre', full_name='FLmonResponse.pre', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sul', full_name='FLmonResponse.sul', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crl', full_name='FLmonResponse.crl', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=370,
)


_FLMONRESPONSEMANAGEMENT = _descriptor.Descriptor(
  name='FLmonResponseManagement',
  full_name='FLmonResponseManagement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=397,
)

_FLMONREQUESTMANAGEMENT.oneofs_by_name['_acc_class'].fields.append(
  _FLMONREQUESTMANAGEMENT.fields_by_name['acc_class'])
_FLMONREQUESTMANAGEMENT.fields_by_name['acc_class'].containing_oneof = _FLMONREQUESTMANAGEMENT.oneofs_by_name['_acc_class']
_FLMONREQUESTMANAGEMENT.oneofs_by_name['_rou_pred'].fields.append(
  _FLMONREQUESTMANAGEMENT.fields_by_name['rou_pred'])
_FLMONREQUESTMANAGEMENT.fields_by_name['rou_pred'].containing_oneof = _FLMONREQUESTMANAGEMENT.oneofs_by_name['_rou_pred']
DESCRIPTOR.message_types_by_name['FLmonRequest'] = _FLMONREQUEST
DESCRIPTOR.message_types_by_name['FLmonRequestManagement'] = _FLMONREQUESTMANAGEMENT
DESCRIPTOR.message_types_by_name['FLmonResponse'] = _FLMONRESPONSE
DESCRIPTOR.message_types_by_name['FLmonResponseManagement'] = _FLMONRESPONSEMANAGEMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FLmonRequest = _reflection.GeneratedProtocolMessageType('FLmonRequest', (_message.Message,), {
  'DESCRIPTOR' : _FLMONREQUEST,
  '__module__' : 'FLmon_pb2'
  # @@protoc_insertion_point(class_scope:FLmonRequest)
  })
_sym_db.RegisterMessage(FLmonRequest)

FLmonRequestManagement = _reflection.GeneratedProtocolMessageType('FLmonRequestManagement', (_message.Message,), {
  'DESCRIPTOR' : _FLMONREQUESTMANAGEMENT,
  '__module__' : 'FLmon_pb2'
  # @@protoc_insertion_point(class_scope:FLmonRequestManagement)
  })
_sym_db.RegisterMessage(FLmonRequestManagement)

FLmonResponse = _reflection.GeneratedProtocolMessageType('FLmonResponse', (_message.Message,), {
  'DESCRIPTOR' : _FLMONRESPONSE,
  '__module__' : 'FLmon_pb2'
  # @@protoc_insertion_point(class_scope:FLmonResponse)
  })
_sym_db.RegisterMessage(FLmonResponse)

FLmonResponseManagement = _reflection.GeneratedProtocolMessageType('FLmonResponseManagement', (_message.Message,), {
  'DESCRIPTOR' : _FLMONRESPONSEMANAGEMENT,
  '__module__' : 'FLmon_pb2'
  # @@protoc_insertion_point(class_scope:FLmonResponseManagement)
  })
_sym_db.RegisterMessage(FLmonResponseManagement)



_FLMON = _descriptor.ServiceDescriptor(
  name='FLmon',
  full_name='FLmon',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=399,
  serialized_end=457,
  methods=[
  _descriptor.MethodDescriptor(
    name='transportFLmon',
    full_name='FLmon.transportFLmon',
    index=0,
    containing_service=None,
    input_type=_FLMONREQUEST,
    output_type=_FLMONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FLMON)

DESCRIPTOR.services_by_name['FLmon'] = _FLMON

# @@protoc_insertion_point(module_scope)
